In [1]:
import numpy as np

arr = np.array([2, 4, 8])
print(arr)

[2 4 8]


In [2]:
element = arr[1]
print(element)

4


In [5]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matrix: ",matrix)

Matrix:  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
element = matrix[2, 2]
print(element)


9


In [17]:
a = np.zeros(6)
print(a)

b = np.ones(6)
print(b)

c = np.empty(6)
print(c)

d = np.arange(100)
print(d)

e = np.linspace(0, 1, num = 6)
print(e)

f = np.ones(6, dtype=np.int64)
f

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0.  0.2 0.4 0.6 0.8 1. ]


array([1, 1, 1, 1, 1, 1])

In [22]:
arr = np.array([1, 4, 7, 9, 6])
print(arr)

arr = np.sort(arr)
print(arr)

arr = np.sort(arr)[::-1]
print(arr)

arr = np.append(arr, 10)
print(arr)

arr = np.delete(arr, 4)
print(arr)


[1 4 7 9 6]
[1 4 6 7 9]
[9 7 6 4 1]
[ 9  7  6  4  1 10]
[ 9  7  6  4 10]


In [25]:
matrix = np.array([[1, 4, 3], [2, 5, 9], [4, 0, 3]])

sorted_col = np.sort(matrix, axis = 1)
print(sorted_col)

sorted_col = -np.sort(matrix, axis = 1)
print(sorted_col)

sorted_row = np.sort(matrix, axis = 0)
print(sorted_row)

sorted_row = -np.sort(matrix, axis = 0)
print(sorted_row)


[[1 3 4]
 [2 5 9]
 [0 3 4]]
[[-1 -3 -4]
 [-2 -5 -9]
 [ 0 -3 -4]]
[[1 0 3]
 [2 4 3]
 [4 5 9]]
[[-1  0 -3]
 [-2 -4 -3]
 [-4 -5 -9]]


In [26]:
matrix = np.array([[1, 4, 3], [2, 5, 9]])

dimension = matrix.ndim
size = matrix.size
shape = matrix.shape

print("Dimension: ", dimension)
print("Size: ", size)
print("Shape: ", shape)

Dimension:  2
Size:  6
Shape:  (2, 3)


In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr_float = arr.astype(float)
print(arr_float)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
arr = np.array([1 ,4, 5 ,3 ,7 ,2])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)
reshaped_arr = arr.reshape(3, 2)
print(reshaped_arr)

reshaped_arr = reshaped_arr.flatten()
print(reshaped_arr)


[[1 4 5]
 [3 7 2]]
[[1 4]
 [5 3]
 [7 2]]
[1 4 5 3 7 2]


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

sub_arr = arr[2:5]
print(sub_arr)

sub_arr = arr[:-5]
print(sub_arr)

sub_arr = arr[-3:]
print(sub_arr)


[3 4 5]
[1 2 3 4]
[7 8 9]


In [43]:
arr = np.array([[1 ,3, 7],[2, 8, 6]])
print(arr)

transposed_arr = arr.T
print(transposed_arr)

[[1 3 7]
 [2 8 6]]
[[1 2]
 [3 8]
 [7 6]]


In [44]:
arr_1 = np.array([1 ,4 ,7])
arr_2 = np.array([2 ,5 ,8])

arr = np.concatenate((arr_1, arr_2))
print(arr)

[1 4 7 2 5 8]


In [47]:
arr = np.array([1 ,3, 7, 2, 8, 6])

total = np.sum(arr)
print("Sum of all elements: ", total)

average = np.average(arr)
print("Average of all elements: ", average)

max_value = np.max(arr)
min_value = np.min(arr)
print("Max value: ", max_value)
print("Min value: ", min_value)

standard_deviation = np.std(arr)
print("Standard deviation: ", standard_deviation)

variance = np.var(arr)
print("Variance of array: ", variance)

arr_1 = np.array([1 ,3, 7])
arr_2 = np.array([2 ,8, 6])

dot_product = np.dot(arr_1, arr_2)
print("Dot product of two arrays: ", dot_product)



Sum of all elements:  27
Average of all elements:  4.5
Max value:  8
Min value:  1
Standard deviation:  2.6299556396765835
Variance of array:  6.916666666666667
Dot product of two arrays:  68
